#!/usr/bin/env bash
#
# A simple wrapper to excute nuker as a cron job

if [[ $# -ne 2 ]];
then
  echo >&2 "[Usage]: $(basename $0) /path/to/config.toml /path/to/.aws [email_address]"
  echo -e >&2 "\t1. Absolute path to the nuker configuraiton file"
  echo -e >&2 "\t2. Absolute path to AWS credentials file, usually generated by running 'aws configure'"
  echo -e >&2 "\t3. (Optional) Email address to send the log file to. Expects mailx to be configured."

  exit 1
fi

# Check if docker is available
command -v docker >/dev/null 2>&1 || {
  echo >&2 "'docker' command not found"
  exit 2
}

start_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
log_file=/var/tmp/nuker-${start_time}.log

echo "Logging to ${log_file}"

docker run --rm -it \
-v $1:/home/nuker/config.toml \
-v $2:/home/nuker/.aws \
ashrithr/nuker:latest \
--profile default \
--config /home/nuker/config.toml \
-vvvv > $log_file 2>&1


if [[ $# -eq 3 ]]; then
  command -v mailx >/dev/null 2>&1 || {
    echo >&2 "'mailx' command not found, skipping send mail"
    exit 2
  }

  mailx -s "Nuker Run Log - ${start_time}" -a $log_file $3
fi